version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

volumes:
  mosquitto_data: