version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ../certs/ca.crt:/mosquitto/config/ca.crt:ro
      - ../certs/shared.crt:/mosquitto/config/shared.crt:ro
      - ../certs/shared.key:/mosquitto/config/shared.key:ro
