version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ../certs/ca.crt:/mosquitto/config/ca.crt:ro
      - ../certs/shared.crt:/mosquitto/config/shared.crt:ro
      - ../certs/shared.key:/mosquitto/config/shared.key:ro

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    restart: always
    depends_on:
      - mosquitto
    container_name: server
    env_file:
      - ../.env

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    restart: always
    depends_on:
      - server
    container_name: client
    env_file:
      - ../.env
